server:
  port: 8001

spring.datasource:
  url: jdbc:mysql://192.168.75.128:3306/parking
  username: parking
  password: 1qaz@WSX
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  database: MYSQL
  hibernate.ddl-auto: update
  show-sql: true